export enum CollectionName {
  companies = 'Companies',
  companyBranch = 'CompanyBranch',
  admins = 'Admins',
  employeeRoles = 'EmployeeRoles',
  employees = 'Employees',
  shifts = 'Shifts',
  patrols = 'Patrols',
  patrolLogs = 'PatrolLogs',
  messages = 'Messages',
  loggedInUsers = 'LoggedInUsers',
  locations = 'Locations',
  reportCategories = 'ReportCategories',
  reports = 'Reports',
  invoices = 'Invoices',
  clients = 'Clients',
  documentCategories = 'DocumentCategories',
  documents = 'Documents',
  settings = 'Settings',
  superAdmin = 'SuperAdmin',
  equipments = 'Equipments',
  equipmentAllocations = 'EquipmentAllocations',
  employeesDAR = 'EmployeesDAR',
  visitors = 'Visitors',
  keys = 'Keys',
  keyAllocations = 'KeyAllocations',
  tasks = 'Tasks',
  taskLogs = 'TaskLogs',
  shiftexchange = 'ShiftExchange',
  shiftoffer = 'ShiftOffer',
  notification = 'Notification',
}

export enum IUserType {
  ADMIN = 'admin',
  SUPER_ADMIN = 'super_admin',
}
